---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: {{ .Release.Name }}
  namespace: apps
spec:
  chart:
    spec:
      chart: minecraft-java
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: truecharts
  interval: 50m
  values:
    common:
      configmap:
        settings:
          data:
            settings.yml: |
              bind:
                ip: 0.0.0.0
                port: 25565
              bossBar:
                enable: false
              brandName:
                content: Limbo
                enable: true
              debugLevel: 1
              dimension: THE_END
              gameMode: 3
              headerAndFooter:
                enable: false
              infoForwarding:
                secret: >-
                  {{`{{ (lookup "v1" "Secret" .Release.Namespace
                  "infisical-managed-secrets").data.VELOCITY_FORWARDING_SECRET | b64dec }}`}}
                type: MODERN
              joinMessage:
                enable: false
              maxPlayers: 100
              netty:
                threads:
                  bossGroup: 1
                  workerGroup: 2
                useEpoll: true
              ping:
                description: >-
                  {"text": "Welcome to the Limbo Minecraft Server: {{ .Release.Name | title
                  }}"}
                version: NanoLimbo
              playerList:
                enable: false
                username: NanoLimbo
              readTimeout: 30000
              spawnPosition:
                pitch: 0
                x: 0
                'y': 64
                yaw: 0
                z: 0
              title:
                enable: false
          enabled: true
          namespace: apps
    service:
      main:
        ports:
          query:
            enabled: false
      rcon:
        enabled: false
    workload:
      main:
        podSpec:
          containers:
            main:
              env:
                COPY_CONFIG_DEST: /data
                MEMORY: 128M
                TYPE: NANOLIMBO
              resources:
                limits:
                  cpu: 500m
                  memory: 320Mi
                requests:
                  cpu: 50m
                  memory: 128Mi
            mcbackup:
              enabled: false
          labels:
            kuvel.azisaba.net/enable-server-discovery: "true"
            kuvel.azisaba.net/initial-server: "true"
            kuvel.azisaba.net/preferred-server-name: {{ .Release.Name }}
    persistence:
      backups:
        enabled: false
      data:
        enabled: true
        size: 500Mi
        type: emptyDir
      settings:
        defaultMode: "0664"
        enabled: true
        expandObjectName: true
        mountPath: /config/settings.yml
        objectName: settings
        subPath: settings.yml
        type: configmap
    podOptions:
      hostUsers: true
    portal:
      open:
        enabled: false
