---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: {{ .Release.Name }}
  namespace: apps
spec:
  chart:
    spec:
      chart: minecraft-java
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: truecharts
  interval: 50m
  values:
    common:
      configmap:
        settings:
          data:
            server.properties: |
              forwarding-secrets={{`{{ (lookup "v1" "Secret" "apps" "minecraft-proxy-velocity").data.VELOCITY_FORWARDING_SECRET | b64dec }}`}}
              velocity-modern=true
          enabled: true
          namespace: apps
    service:
      main:
        ports:
          query:
            enabled: false
      rcon:
        enabled: false
    workload:
      main:
        podSpec:
          containers:
            main:
              env:
                COPY_CONFIG_DEST: /data
                ENABLE_QUERY: false
                MAX_WORLD_SIZE: 250
                MOTD: "Welcome to the Limbo Minecraft Server: {{ .Release.Name }}"
                NETWORK_COMPRESSION_THRESHOLD: 256
                ONLINE_MODE: false
                SIMULATION_DISTANCE: 4
                SNOOPER_ENABLED: false
                TYPE: LIMBO
                USE_AIKAR_FLAGS: true
                VIEW_DISTANCE: 7
            mcbackup:
              enabled: false
          labels:
            kuvel.azisaba.net/enable-server-discovery: "true"
            kuvel.azisaba.net/initial-server: "true"
            kuvel.azisaba.net/preferred-server-name: {{ .Release.Name }}
    persistence:
      backups:
        enabled: false
      data:
        enabled: true
        size: 500Mi
        type: emptyDir
      server-properties:
        defaultMode: "0664"
        enabled: true
        expandObjectName: true
        mountPath: /config/server.properties
        objectName: settings
        subPath: server.properties
        type: configmap
    portal:
      open:
        enabled: false
