---
apiVersion: shulkermc.io/v1alpha1
kind: MinecraftServer
metadata:
  name: {{ .Release.Name }}
  namespace: apps
spec:
  clusterRef:
    name: minecraft-cluster
  config:
    disableEnd: false
    disableNether: false
    plugins:
{{ toYaml .Values.plugins | indent 4 }}
  podOverrides:
    volumeMounts:
      - name: world
        mountPath: /data/world
      - name: nether
        mountPath: /data/world_nether
      - name: end
        mountPath: /data/world_the_end
    volumes:
      -  name: world
         persistentVolumeClaim:
           claimName: {{ .Release.Name }}-world
           readOnly: false
      -  name: nether
         persistentVolumeClaim:
           claimName: {{ .Release.Name }}-nether
           readOnly: false
      -  name: end
         persistentVolumeClaim:
           claimName: {{ .Release.Name }}-end
           readOnly: false
  tags:
    - {{ .Release.Name }}
  version:
    channel: Paper
    customJar:
      url: https://api.purpurmc.org/v2/purpur/{{ .Values.minecraftVersion }}/latest/download
    name: {{ .Values.minecraftVersion }}
