accessType: ingress
ingressClassName: ""
diskSpace: 10Gi
domain: ""
nodePort: 30000
modrinthProjects:
  - explorers-compass
  - journeymap
  - natures-compass
  - pixelmon
spigotPluginIds:
  - 6245 # PlaceholderAPI
  - 28140 # LuckPerms
  - 34315 # Vault
  - 81534 # Chunky
  - 84278 # ChunkyBorder
storageClass: spot-ceph
worldUrl: ""
