---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: {{ .Release.Name }}-pixelmon
  namespace: apps
spec:
  chart:
    spec:
      chart: minecraft-java
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: truecharts
  interval: 50m
  values:
    common:
      configmap:
        settings:
          data:
            bukkit.yml: |
              spawn-limits:
                ambient: 1
                animals: 5
                axolotls: 3
                monsters: 20
                water-ambient: 2
                water-animals: 2
                water-underground-creature: 3
              ticks-per:
                ambient-spawns: 400
                animal-spawns: 400
                axolotl-spawns: 400
                monster-spawns: 10
                water-ambient-spawns: 400
                water-spawns: 400
                water-underground-creature-spawns: 400
            paper.yml: |
              settings:
                velocity-support:
                  enabled: true
            paper-global.yml: |
              proxies:
                velocity:
                  enabled: true
            purpur.yml: |
              dolphin:
                disable-treasure-searching: true
              entities-can-use-portals: false
              teleport-if-outside-border: true
              use-alternate-keepalive: true
              villager:
                lobotomize:
                  enabled: true
                search-radius:
                  acquire-poi: 16
                  nearest-bad-sensor: 16
              zombie:
                aggressive-towards-villager-when-lagging: false
          enabled: true
          namespace: apps
    service:
      main:
        ports:
          query:
            enabled: false
      rcon:
        enabled: true
    workload:
      main:
        podSpec:
          containers:
            main:
              env:
                COPY_CONFIG_DEST: /data
                DIFFICULTY: normal
                ENABLE_QUERY: false
                LUCKPERMS_DATA_ADDRESS:
                  secretKeyRef:
                    expandObjectName: false
                    key: ADDRESS
                    name: minecraft-proxy-luckperms
                LUCKPERMS_DATA_DATABASE:
                  secretKeyRef:
                    expandObjectName: false
                    key: DATABASE
                    name: minecraft-proxy-luckperms
                LUCKPERMS_DATA_PASSWORD:
                  secretKeyRef:
                    expandObjectName: false
                    key: PASSWORD
                    name: minecraft-proxy-luckperms
                LUCKPERMS_DATA_POOL_SETTINGS_MAXIMUM_POOL_SIZE:
                  secretKeyRef:
                    expandObjectName: false
                    key: POOL_SETTINGS_MAXIMUM_POOL_SIZE
                    name: minecraft-proxy-luckperms
                LUCKPERMS_DATA_USERNAME:
                  secretKeyRef:
                    expandObjectName: false
                    key: USERNAME
                    name: minecraft-proxy-luckperms
                LUCKPERMS_MESSAGING_SERVICE: pluginmsg
                LUCKPERMS_STORAGE_METHOD:
                  secretKeyRef:
                    expandObjectName: false
                    key: STORAGE_METHOD
                    name: minecraft-proxy-luckperms
                LUCKPERMS_SYNC_MINUTES: -1
                MAX_WORLD_SIZE: 2500
                MODRINTH_ALLOWED_VERSION_TYPE: beta
                MODRINTH_DOWNLOAD_DEPENDENCIES: required
                MODRINTH_PROJECTS: {{ default "" (join "," .Values.modrinthProjects) }}
                MOTD: "Welcome to the Pixelmon Minecraft Server: {{ .Release.Name }}"
                NETWORK_COMPRESSION_THRESHOLD: 256
                ONLINE_MODE: false
                PAPER_CONFIG_REPO: https://raw.githubusercontent.com/Alpha018/paper-config-optimized/main
                PAPER_VELOCITY_SECRET: 
                  secretKeyRef:
                    expandObjectName: false
                    key: VELOCITY_FORWARDING_SECRET
                    name: minecraft-proxy-velocity
                PLUGIN: https://hangarcdn.papermc.io/plugins/Flyte/PluginPortal/versions/2.2.0/PAPER/PluginPortal-2.2.0.jar
                PVP: true
                RCON_ENABLED: false
                SIMULATION_DISTANCE: 4
                SNOOPER_ENABLED: false
                TYPE: KETTING
                USE_AIKAR_FLAGS: true
                VERSION: 1.20
                VIEW_DISTANCE: 7
                {{ if .Values.worldUrl }}
                WORLD: {{ .Values.worldUrl }}
                {{ end }}
            mcbackup:
              enabled: false
          labels:
            kuvel.azisaba.net/enable-server-discovery: "true"
            kuvel.azisaba.net/preferred-server-name: {{ .Release.Name }}-pixelmon
    persistence:
      backups:
        enabled: false
      bukkit:
        defaultMode: "0664"
        enabled: true
        expandObjectName: true
        mountPath: /config/bukkit.yml
        objectName: settings
        subPath: bukkit.yml
        type: configmap
      data:
        enabled: true
        size: 7Gi
        storageClass: sata
        type: pvc
      paper:
        defaultMode: "0664"
        enabled: true
        expandObjectName: true
        mountPath: /config/paper.yml
        objectName: settings
        subPath: paper.yml
        type: configmap
      paper-global:
        defaultMode: "0664"
        enabled: true
        expandObjectName: true
        mountPath: /config/config/paper-global.yml
        objectName: settings
        subPath: paper-global.yml
        type: configmap
      purpur:
        defaultMode: "0664"
        enabled: true
        expandObjectName: true
        mountPath: /config/purpur.yml
        objectName: settings
        subPath: purpur.yml
        type: configmap
    portal:
      open:
        enabled: false
