---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: {{ .Release.Name }}
  namespace: apps
spec:
  chart:
    spec:
      chart: minecraft-java
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: truecharts
  interval: 50m
  values:
    common:
      configmap:
        patch:
          data:
            patches.json: |
              {
                "patches": [
                  {
                    "file": "/data/bukkit.yml",
                    "ops": [
                      {
                        "$put": {
                          "path": "$.['spawn-limits'].monsters",
                          "value": "20",
                          "value-type": "int"
                        }
                      },
                      {
                        "$put": {
                          "path": "$.['spawn-limits'].animals",
                          "value": "5",
                          "value-type": "int"
                        }
                      },
                      {
                        "$put": {
                          "path": "$.['spawn-limits'].water-animals",
                          "value": "2",
                          "value-type": "int"
                        }
                      },
                      {
                        "$put": {
                          "path": "$.['spawn-limits'].water-ambient",
                          "value": "2",
                          "value-type": "int"
                        }
                      },
                      {
                        "$put": {
                          "path": "$.['spawn-limits'].water-underground-creature",
                          "value": "3",
                          "value-type": "int"
                        }
                      },
                      {
                        "$put": {
                          "path": "$.['spawn-limits'].axolotls",
                          "value": "3",
                          "value-type": "int"
                        }
                      },
                      {
                        "$put": {
                          "path": "$.['spawn-limits'].ambient",
                          "value": "1",
                          "value-type": "int"
                        }
                      },
                      {
                        "$put": {
                          "path": "$.['ticks-per'].monster-spawns",
                          "value": "10",
                          "value-type": "int"
                        }
                      },
                      {
                        "$put": {
                          "path": "$.['ticks-per'].animal-spawns",
                          "value": "400",
                          "value-type": "int"
                        }
                      },
                      {
                        "$put": {
                          "path": "$.['ticks-per'].water-spawns",
                          "value": "400",
                          "value-type": "int"
                        }
                      },
                      {
                        "$put": {
                          "path": "$.['ticks-per'].water-ambient-spawns",
                          "value": "400",
                          "value-type": "int"
                        }
                      },
                      {
                        "$put": {
                          "path": "$.['ticks-per'].water-underground-creature-spawns",
                          "value": "400",
                          "value-type": "int"
                        }
                      },
                      {
                        "$put": {
                          "path": "$.['ticks-per'].axolotl-spawns",
                          "value": "400",
                          "value-type": "int"
                        }
                      },
                      {
                        "$put": {
                          "path": "$.['ticks-per'].ambient-spawns",
                          "value": "400",
                          "value-type": "int"
                        }
                      }
                    ]
                  },
                  {
                    "file": "/data/config/paper-global.yml",
                    "ops": [
                      {
                        "$put": {
                          "path": "$.proxies.velocity.enabled",
                          "value": "true",
                          "value-type": "bool"
                        }
                      }
                    ]
                  },
                  {
                    "file": "/data/paper.yml",
                    "ops": [
                      {
                        "$put": {
                          "path": "$.settings['velocity-support'].enabled",
                          "value": "true",
                          "value-type": "bool"
                        }
                      }
                    ]
                  },
                  {
                    "file": "/data/purpur.yml",
                    "ops": [
                      {
                        "$put": {
                          "path": "$.['use-alternate-keepalive']",
                          "value": "true",
                          "value-type": "bool"
                        }
                      },
                      {
                        "$put": {
                          "path": "$.zombie.['aggressive-towards-villager-when-lagging']",
                          "value": "false",
                          "value-type": "bool"
                        }
                      },
                      {
                        "$put": {
                          "path": "$.['entities-can-use-portals']",
                          "value": "false",
                          "value-type": "bool"
                        }
                      },
                      {
                        "$put": {
                          "path": "$.villager.lobotomize.enabled",
                          "value": "true",
                          "value-type": "bool"
                        }
                      },
                      {
                        "$put": {
                          "path": "$.villager.['search-radius'].acquire-poi",
                          "value": "16",
                          "value-type": "int"
                        }
                      },
                      {
                        "$put": {
                          "path": "$.villager.['search-radius'].nearest-bad-sensor",
                          "value": "16",
                          "value-type": "int"
                        }
                      },
                      {
                        "$put": {
                          "path": "$.dolphin.['disable-treasure-searching']",
                          "value": "true",
                          "value-type": "bool"
                        }
                      },
                      {
                        "$put": {
                          "path": "$.['teleport-if-outside-border']",
                          "value": "true",
                          "value-type": "bool"
                        }
                      }
                    ]
                  }
                ]
              }

          enabled: true
          namespace: apps
    service:
      main:
        ports:
          query:
            enabled: false
      rcon:
        enabled: false
    workload:
      main:
        podSpec:
          containers:
            main:
              env:
                DIFFICULTY: normal
                ENABLE_QUERY: false
                MAX_WORLD_SIZE: 2500
                MOTD: "Welcome to the Vanilla Minecraft Server: {{ .Release.Name }}"
                NETWORK_COMPRESSION_THRESHOLD: 256
                ONLINE_MODE: false
                PAPER_CONFIG_REPO: https://raw.githubusercontent.com/Alpha018/paper-config-optimized/main
                PAPER_VELOCITY_SECRET: 
                  secretKeyRef:
                    expandObjectName: false
                    key: VELOCITY_FORWARDING_SECRET
                    name: minecraft-proxy-velocity
                PATCH_DEFINITIONS: /tmp/patches.json
                PLUGINS: {{ default "" (join "," .Values.plugins) }}
                PVP: true
                RCON_ENABLED: false
                SIMULATION_DISTANCE: 4
                SNOOPER_ENABLED: false
                TYPE: PURPUR
                USE_AIKAR_FLAGS: true
                VERSION: {{ .Values.minecraftVersion }}
                VIEW_DISTANCE: 7
                {{ if .Values.worldUrl }}
                WORLD: {{ .Values.worldUrl }}
                {{ end }}
            mcbackup:
              enabled: false
          labels:
            kuvel.azisaba.net/enable-server-discovery: "true"
            kuvel.azisaba.net/preferred-server-name: {{ .Release.Name }}
    persistence:
      backups:
        enabled: false
      data:
        enabled: true
        size: 7Gi
        type: emptyDir
      patches:
        defaultMode: "0664"
        enabled: true
        expandObjectName: true
        mountPath: /tmp/patches.json
        objectName: patch
        subPath: patches.json
        type: configmap
    portal:
      open:
        enabled: false
