---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: {{ .Release.Name }}
  namespace: apps
spec:
  chart:
    spec:
      chart: minecraft-java
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: truecharts
  interval: 50m
  values:
    service:
      main:
        ports:
          query:
            enabled: false
      rcon:
        enabled: false
    workload:
      main:
        podSpec:
          containers:
            main:
              env:
                DIFFICULTY: normal
                ENABLE_QUERY: false
                MAX_WORLD_SIZE: 2500
                MOTD: "Welcome to the Vanilla Minecraft Server: {{ .Release.Name }}"
                NETWORK_COMPRESSION_THRESHOLD: 256
                ONLINE_MODE: false
                PAPER_CONFIG_REPO: https://raw.githubusercontent.com/Alpha018/paper-config-optimized/main
                PAPER_VELOCITY_SECRET: 
                  secretKeyRef:
                    expandObjectName: false
                    key: VELOCITY_FORWARDING_SECRET
                    name: minecraft-proxy-velocity
                PLUGINS: {{ default "" (join "," .Values.plugins) }}
                PVP: true
                SIMULATION_DISTANCE: 4
                SNOOPER_ENABLED: false
                TYPE: PURPUR
                USE_AIKAR_FLAGS: true
                VERSION: {{ .Values.minecraftVersion }}
                VIEW_DISTANCE: 7
                {{ if .Values.worldUrl }}
                WORLD: {{ .Values.worldUrl }}
                {{ end }}
            mcbackup:
              enabled: false
          labels:
            kuvel.azisaba.net/enable-server-discovery: "true"
            kuvel.azisaba.net/preferred-server-name: {{ .Release.Name }}
    persistence:
      backups:
        enabled: false
      data:
        enabled: true
        size: 7Gi
        type: emptyDir
    portal:
      open:
        enabled: false
