accessType: ingress
ingressClassName: ""
diskSpace: 7Gi
domain: ""
nodePort: 30000
modrinthProjects: []
spigotPluginIds:
  - 6245 # PlaceholderAPI
  - 28140 # LuckPerms
  - 34315 # Vault
  - 81534 # Chunky
  - 84278 # ChunkyBorder
storageClass: spot-ceph
worldUrl: ""
